permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
  
paginate: 10
paginate_path: ":num"
baseurl: ""

title: "Steve Senior"
email: "ssenior45@googlemail.com"
description: "Technology enthusiast"
github_username:  "ssenior45"
swiftype_searchId: "Xi3WsimxQzyCP1UUDaV3"
disqus_shortname: "ssenior45"

#
url: "http://stevensenior.co.uk"
imgrepo: "http://stevensenior.co.uk/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

blog_title: "Steve Senior"
blog_description: "Technology enthusiast"
site_url: "http://stevensenior.co.uk"
twitter_format: "@title @url@tags"
twitter_url_length: 22
twitter_max_length: 140

gems: [jekyll-paginate]
